<?php

print "<link rel='stylesheet' id='estilo-css'  href='https://www.expertsphp.com/wp-content/plugins/simple-code-highlighter/estilo.css?ver=4.9.9' type='text/css' media='all' />\n";
print "<link rel='stylesheet' id='aquarella-style-css'  href='https://www.expertsphp.com/wp-content/themes/aquarella-lite/style.css?ver=4.9.9' type='text/css' media='all' />\n";
print "<link rel='stylesheet' id='bootstrap-css'  href='https://www.expertsphp.com/wp-content/themes/aquarella-lite/vendor/bootstrap/css/bootstrap.min.css?ver=4.9.9' type='text/css' media='all' />\n";
print "<link rel='stylesheet' id='aquarella-googlewebfonts-css'  href='https://fonts.googleapis.com/css?family=Merriweather+Sans%3A400%2C700&ver=4.9.9' type='text/css' media='all' />\n";
print "<link rel='stylesheet' id='aquarella-googlewebfonts2-css'  href='https://fonts.googleapis.com/css?family=Roboto%3A400%2C700%2C300&ver=4.9.9' type='text/css' media='all' />\n";
print "<link rel='stylesheet' id='aquarella-theme-style-css'  href='https://www.expertsphp.com/wp-content/themes/aquarella-lite/css/styles.css?ver=4.9.9' type='text/css' media='all' />\n";
print "<script type='text/javascript' src='/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>\n";
print "<script type='text/javascript' src='/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>\n";
print "<link rel='https://api.w.org/' href='https://www.expertsphp.com/wp-json/' />\n";
print "\n";
print "<link rel=\"icon\" href=\"https://www.expertsphp.com/wp-content/uploads/2019/01/cropped-fev-icon-32x32.png\" sizes=\"32x32\" />\n";
print "<link rel=\"icon\" href=\"https://www.expertsphp.com/wp-content/uploads/2019/01/cropped-fev-icon-192x192.png\" sizes=\"192x192\" />\n";
print "<link rel=\"apple-touch-icon-precomposed\" href=\"https://www.expertsphp.com/wp-content/uploads/2019/01/cropped-fev-icon-180x180.png\" />\n";
print "<meta name=\"msapplication-TileImage\" content=\"https://www.expertsphp.com/wp-content/uploads/2019/01/cropped-fev-icon-270x270.png\" />\n";
print "<!-- Customizer Variables -->\n";
print "<!-- Customizer Styles -->\n";
print "<style>\n";
print "      .adimg{position: absolute;width: 160px}\n";
print "            .adleft{left: -70px}\n";
print "            .adright{right: -70px}\n";
print "            .adleft-fix{position: fixed;left: 20px;top: 10px;z-index: 0}\n";
print "            .adright-fix{position: fixed;right: 20px;top: 10px;z-index: 0}\n";
print "            footer{z-index:9;position:relative;}\n";
print "            @media(max-width: 767px){\n";
print "              .mnone{display: none;}\n";
print "            }\n";
print "            \n";
print "         \n";
print "         .color1,\n";
print "         a,\n";
print "         .title-of-section,\n";
print "         .btn-stroke,\n";
print "         .tags-links a,\n";
print "         .tbpw-profile-name,\n";
print "         .navigation a:hover,\n";
print "         .comment-reply-link {\n";
print "         color: #f72565;\n";
print "         }\n";
print "         .color2 {\n";
print "         color: #ffcf38;\n";
print "         }\n";
print "         .color3,\n";
print "         a:hover,\n";
print "         .sidebar-area .widget-list li a:hover,\n";
print "         .sidebar-area .widget ul li a:hover,\n";
print "         .entry-footer .cat-links a,\n";
print "         .navigation a {\n";
print "         color: #f8be27;\n";
print "         }\n";
print "         html,\n";
print "         #colophon .widget {\n";
print "         background-color: transparent;\n";
print "         }\n";
print "         body,\n";
print "         .body-boxed {\n";
print "         background-color: #fafafa;\n";
print "         }\n";
print "         .bdw-wrapper:before,\n";
print "         .bdw-wrapper:after,\n";
print "         .title-border:after,\n";
print "         .btn-default,\n";
print "         .balloon,\n";
print "         .balloon:after,\n";
print "         .dropdown-mega-content,\n";
print "         .dropdown-mega-content ul.dropdown-mega-sub-nav li a:hover,\n";
print "         .navbar-top,\n";
print "         .tagcloud a,\n";
print "         .footer-social-icons .social-icons-list a:hover,\n";
print "         .btn-special, .btn,\n";
print "         .section-title,\n";
print "         .social-icons a,\n";
print "         .navbar .nav  li  a:hover, .navbar .nav  li  a:focus, .navbar .nav  li  a:active,\n";
print "         .wpcf7-form input[type=submit], .mc4wp-form input[type=submit] {\n";
print "         background-color: #f72565;\n";
print "         }\n";
print "         .bdw-wrapper-negative:before,\n";
print "         .bdw-wrapper-negative:after,\n";
print "         .header-social-icons ul a,\n";
print "         .header-social-icons ul a:hover {\n";
print "         background-color: #ffffff;\n";
print "         }\n";
print "         .btn-default,\n";
print "         .btn-special:hover,\n";
print "         .balloon,\n";
print "         #masthead,\n";
print "         #masthead a,\n";
print "         .navbar-toggle,\n";
print "         .dropdown-mega-content,\n";
print "         #colophon,\n";
print "         #colophon a,\n";
print "         #colophon .footer-bottom,\n";
print "         #colophon .widget,\n";
print "         #colophon .widget p,\n";
print "         .section-title,\n";
print "         .section-mini-hero,\n";
print "         .sidebar-area .widget-title,\n";
print "         .sidebar-area .widget h3,\n";
print "         .entry-footer .cat-links a:hover,\n";
print "         .entry-footer .comments-link a,\n";
print "         .entry-meta,\n";
print "         .entry-meta a,\n";
print "         .comments-area input[type=submit]:hover,\n";
print "         .wpcf7-form input[type=submit] {\n";
print "         color: #ffffff;\n";
print "         }\n";
print "         body .btn-special,\n";
print "         body .btn-stroke:hover,\n";
print "         body .btn-stroke-negative,\n";
print "         body .tagcloud a,\n";
print "         body .tagcloud a:hover,\n";
print "         body .footer-social-icons .social-icons-list a,\n";
print "         body .footer-social-icons .social-icons-list a:hover,\n";
print "         body .contrast-with-image,\n";
print "         body .social-icons a,\n";
print "         body .post-element-header,\n";
print "         body .comments-area input[type=submit],\n";
print "         body .hero-slideshow {\n";
print "         color: #ffffff ;\n";
print "         }\n";
print "         body .btn-stroke {\n";
print "         border-color: #f72565;\n";
print "         }\n";
print "         body .btn-stroke:before,\n";
print "         body .navbar .nav li a,\n";
print "         body .post-element-header,\n";
print "         body .owl-carousel .owl-dot.active span {\n";
print "         background-color: #f8be27;\n";
print "         }\n";
print "         body .btn-stroke:hover {\n";
print "         border-color: #f8be27; \n";
print "         }\n";
print "         body .btn-stroke:hover {\n";
print "         background-color: transparent;\n";
print "         }\n";
print "         body .btn-stroke-negative {\n";
print "         border-color: #ffffff ;\n";
print "         }\n";
print "         .form-control,\n";
print "         .comments-area input[type=text],\n";
print "         .comments-area input[type=email],\n";
print "         .comments-area input[type=url],\n";
print "         .comments-area textarea {\n";
print "         color: #111;\n";
print "         }\n";
print "         .navbar-toggle {\n";
print "         border-color: #ffffff;\n";
print "         }\n";
print "         .navbar-bottom,\n";
print "         .social-icons a:hover {\n";
print "         background-color: #ffcf38;\n";
print "         }\n";
print "         body .header-social-icons ul a {\n";
print "         color: #f8be27;\n";
print "         }\n";
print "         body .header-social-icons ul a:hover {\n";
print "         color: #f72565;\n";
print "         }\n";
print "         #colophon {\n";
print "         background-color: #444444;\n";
print "         }\n";
print "         .tagcloud a:hover,\n";
print "         .entry-footer .cat-links a:hover,\n";
print "         .entry-footer .comments-link a,\n";
print "         .entry-footer .comments-link a:hover,\n";
print "         .entry-meta {\n";
print "         background-color: #f8be27;\n";
print "         }\n";
print "         .contrast,\n";
print "         .contrast-box {\n";
print "         background-color: #f2f2f2;\n";
print "         }\n";
print "         .sidebar-area .widget-list li a,\n";
print "         .sidebar-area .widget ul li a,\n";
print "         .comment-metadata a {\n";
print "         color: #555;\n";
print "         }\n";
print "         body .sidebar-area .widget_search #s {\n";
print "         border-color: #ccc;\n";
print "         }\n";
print "         .sidebar-area .widget_search #s {\n";
print "         color: #fff;\n";
print "         }\n";
print "         .entry-title,\n";
print "         .entry-title a {\n";
print "         color: #4d4d4f;\n";
print "         }\n";
print "         .entry-footer .cat-links a {\n";
print "         border-color: #f8be27;\n";
print "         }\n";
print "         .comments-area input[type=text],\n";
print "         .comments-area input[type=email],\n";
print "         .comments-area input[type=url],\n";
print "         .comments-area textarea,\n";
print "         .wpcf7-form input[type=text],\n";
print "         .wpcf7-form input[type=email],\n";
print "         .wpcf7-form textarea {\n";
print "         border-color: #ffcf38;\n";
print "         }\n";
print "         .comment-author .fn a {\n";
print "         color: #555555;\n";
print "         }\n";
print "         \n";
print "         #body {\n";
print "         background-image: url(''); \n";
print "         background-color: #eeeeee;\n";
print "         }\n";
print "</style>\n";
print "<div id=\"page\" class=\"site\">\n";
print "  <a class=\"skip-link screen-reader-text\" href=\"#content\">Skip to content</a>\n";
print "  <!-- Header\n";
print "  ================================================== -->\n";
print "  <header id=\"masthead\" class=\"site-header\" role=\"banner\">\n";
print "	\n";
print "  </header>\n";
print "  <!-- /Header\n";
print "  ================================================== -->\n";
print "  <!-- /Content\n";
print "  ================================================== -->\n";
print "  <!-- == CONTENT AREA == -->\n";
print "  <div id=\"primary\" class=\"content-area\">\n";
print "	<div class=\"container\">\n";
print "	  <!-- row -->\n";
print "\n";
print "\n";
print "\n";
print "	  <div class=\"row\">\n";
print "		<!-- col -->\n";
print "		<!--ads-->\n";
print "		<div class=\"col-sm-1 mnone\">\n";
print "		  <div class=\"adimg adleft\">\n";
print "\n";
print "\n";
print "\n";
print "		  </div>\n";
print "		</div>\n";
print "		<div class=\"col-sm-10\">\n";
print "		  <main id=\"main\" class=\"site-main\" role=\"main\">\n";
print "			<article>\n";
print "			  <div class=\"post-element\">\n";
print "				<!-- Featured image -->\n";
print "				<!-- / Featured-image -->\n";
print "				<header class=\"entry-header\">\n";
print "\n";
print "				  <div class=\"text-center\"  id=\"showdata\">\n";
print "\n";
print "					<div class=\"col-sm-12\">\n";
print "\n";
print "\n";
print "\n";
print "					</div>\n";
print "\n";
print "					<div class=\"post-has-ct\"></div>\n";
print "					<h1 class=\"entry-title text-center\">How to Save Facebook, Instagram, Twitter Videos & Images?</h1>\n";
print "\n";
print "					<form method=\"POST\" action=\"/download.php\">\n";
print "					  <div class=\"input-group\" style=\"max-width:570px;text-align:center;margin:0 auto;\">\n";
print "						<input name=\"url\" class=\"form-control input-lg\" placeholder=\"https://twitter.com/MattCaronTV/status/1119533724155224064\" type=\"url\" autofocus=\"\" required>\n";
print "\n";
print "						<span class=\"input-group-btn\">\n";
print "						  <button name=\"submit\" class=\"btn btn-primary btn-lg\">Download</button>\n";
print "						</span>\n";
print "					  </div>\n";
print "					  <div></div>\n";
print "					  <p class=\"text-center\">Example:- <a>https://twitter.com/MattCaronTV/status/1119533724155224064</a></p>\n";
print "					</form>\n";
print "\n";
print "				  </div>\n";
print "\n";
print "\n";
print "				</header>\n";
print "				<!-- .entry-header -->\n";
print "				<div class=\"entry-content\">\n";
print "				</div>\n";
print "				<!-- .entry-content -->\n";
print "			  </div>\n";
print "			</article>\n";
print "			<!-- #post-## -->\n";
print "		  </main>\n";
print "		</div>\n";
print "		<!-- /col -->\n";
print "\n";
print "\n";
print "		<div class=\"col-sm-1 mnone\">\n";
print "\n";
print "		</div>\n";
print "\n";
print "	  </div>\n";
print "	  <!-- / row -->\n";
print "	</div>\n";
print "  </div>\n";
print "  <!-- == /CONTENT AREA == -->\n";
print "</div>\n";
print "\n";
print "<script type='text/javascript' src='https://www.expertsphp.com/wp-content/plugins/simple-code-highlighter/js/pretty.js?ver=4.9.9'></script>\n";
print "<script type='text/javascript' src='https://www.expertsphp.com/wp-content/themes/aquarella-lite/js/navigation.js?ver=20151215'></script>\n";
print "<script type='text/javascript' src='https://www.expertsphp.com/wp-content/themes/aquarella-lite/js/skip-link-focus-fix.js?ver=20151215'></script>\n";
print "<script type='text/javascript' src='/wp-includes/js/comment-reply.min.js?ver=4.9.9'></script>\n";
print "<script type='text/javascript' src='https://www.expertsphp.com/wp-content/themes/aquarella-lite/vendor/bootstrap/js/bootstrap.min.js?ver=20151215'></script>\n";
print "<script type='text/javascript' src='/wp-includes/js/wp-embed.min.js?ver=4.9.9'></script>\n";
print "\n";
print "\n";
print "<style>\n";
print "       .btn-block {\n";
print "           color: white;\n";
print "       }\n";
print "</style>";

?>
